### ISSUE TITLE
Wangguard class XML name conflict

### ISSUE THREAD

**Issue by shookie** [joseconti/WangGuard#9]
We wanted to use the accounts from a pre-existing wordpress forum and blog for our new mediawiki wiki. We used this mediawiki extension for this: http://www.mediawiki.org/wiki/Extension:WPMW

The trouble in doing so is, that in the core mediawiki codebase there is a widely used class Xml.
Since both wordpress and mediawiki are far too old to be written with php namespaces in mind this causes a problem with your wanguard class XML. The naming conflict renders the wiki a useless wite page.

This conflict will always occur whenever there is any interaction between a wordpress install that uses wangguard and any mediawiki install.

Now while it is a bad practice to have a central class name like Xml that is likely to be used in a lot of packages when you don't have namespaces, avoiding this trap for wangguard is easy at this point, since the only three places where the class name occurs is in the class definition itself, in the constructor function and in the one instantiation in the same file.

For our site I renamed your XML class to WANG_XML, an easy enough fix, it is an annoying problem to track down though, and others might want to avoid having to do that,

**Comment by joseconti** [comment]
It is fines for the nexo release

https://github.com/joseconti/WangGuard/commit/bea580f653556f21203c7e27a3c54ac7f94af3a0
https://github.com/joseconti/WangGuard/commit/6000668e3091b579c611defb329a50ac23efa035
